### ISSUE TITLE
A few suggestions

### ISSUE THREAD

**Issue by tony-liuliu** [ExpediaGroup/kubernetes-sidecar-injector#14]
This plugin is very good, but there are a few suggestions.
1. If the namespace exists kubernetes-sidecar-injector: enabled label, the sidecar is automatically injected.
2. If the namespace does not exist kubernetes-sidecar-injector: enabled label, but the deployment's .spec.template.metadata.annotation exists sidecar-injector.expedia.com/inject: true when injecting sidecar.
3. If the namespace has kubernetes-sidecar-injector: enabled label and the deployment's .spec.template.metadata.annotation has sidecar-injector.expedia.com/inject: false, no sidecar is injected.

**Comment by shreyaa-sharma** [comment]
@keshavpeswani Can you have a look at this

**Comment by mvaalexp** [comment]
I have overhauled the webhook triggers (it now runs off the webhook itself rather than checking every pod creation).
The triggers are completely customizable on both the namespace level and the pod level:
https://github.com/ExpediaGroup/kubernetes-sidecar-injector/blob/master/charts/kubernetes-sidecar-injector/values.yaml#L12-L19
You can now use the `sidecar-injector.expedia.com/disable-inject: "true"` label to turn off injections at the pod level.
See here for defaults:
https://github.com/ExpediaGroup/kubernetes-sidecar-injector/blob/master/charts/kubernetes-sidecar-injector/templates/mutatingwebhook-template.yaml#L46-L72

Thanks.
